const books = [
  {
    image: "a_million_to_one.jpg",
    title: "A Million to One",
    author: "Tony Faggiolo",
    genres: [
      "horror fiction",
      "mystery",
      "urban fantasy",
      "paranormal fiction",
      "paranormal fantasy",
    ],
    price: 19.95,
    quantity: 7,
  },
  {
    image: "hp_and_the_goblet_of_fire.jpg",
    title: "Harry Potter and the Goblet of Fire",
    author: "J.K. Rowling",
    genre: ["fantasy"],
    price: 14.99,
    quantity: 10,
  },
  {
    image: "the_great_gatsby.jpg",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: ["tradgedy", "fiction"],
    price: 12.72,
    quantity: 11,
  },
  {
    image: "the_lonely_road_we_traveled.jpg",
    title: "The Lonely Road We Traveled",
    author: "Katherine Moss",
    genre: ["nonfiction"],
    price: 9.99,
    quantity: 2,
  },
  {
    image: "the_ultimate_job_interview.jpg",
    title: "The Ultimate Job Interview",
    author: "Alexander Gordon",
    genre: ["nonfiction"],
    price: 29.99,
    quantity: 3,
  },
  {
    image: "the_war_of_the_worlds.jpg",
    title: "The War of the Worlds",
    author: "H.G. Wells",
    genre: ["classic", "fiction"],
    price: 7.24,
    quantity: 9,
  },
  {
    image: "where_the_crawdads_sing.jpg",
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    genre: ["coming of age", "murder mystery"],
    price: 14.67,
    quantity: 17,
  },
  {
    image: "where_the_wild_things_are.jpg",
    title: "Where the Wild Things Are",
    author: "Maurice Sendak",
    genre: ["childrens"],
    price: 8.15,
    quantity: 13,
  },
];

module.exports = books;
